### ISSUE TITLE
Problem with IMG height="auto"

### ISSUE THREAD

**Issue by mikelawry** [wayou/SlipHover#11]
Hello,
i have a problem with slipHover. 

In my div, i loaded the Image
img src="http://www.lifelenta.ru/images/uploads/files/kNfza5eZV0xwd.jpg" width="25%"

Sliphover doesn't work (doesn't show the overlay). Once i resize the window, it works perfectly fine.

Then, i tried to give the image a height. For example like height="100px" or something. Then, it works fine again (without resize window). 

I tried some commands, and found out: everytime the height of a table or image is set to "auto", Sliphover doesn't work until i resize the window. 

Can you help me fixing that?? because i have to use the height="auto" command to show the images correctly on my homepage.

Thank you,
Marius

**Comment by wayou** [comment]
hi @mikelawry ,

would love to help but I cant reproduce the problem. 
if you can setup a jsfiddle that would be very helpful.
