### ISSUE TITLE
Request: also copy over a links target; $targetAParent.attr('target')

### ISSUE THREAD

**Issue by BennyVL** [wayou/SlipHover#17]
Currently when withLink is true you pick up the href of targetAParent. Could you please do the same for the target attribute of targetAParent?

So in code, something like: 

            $targetAParent = $element.parent('a');
            if ($targetAParent.length && instance.settings.withLink) {
                var url = $targetAParent.attr('href');
                var target = $targetAParent.attr('target'); // <-- NEW
                $overlay = $('<a>', {
                    class: 'sliphover-overlay',
                    href: url || '#',
                    target: target, // <-- NEW
                }).css({
                    textDecoration: 'none'
                });

Thanks!!!

**Comment by wayou** [comment]
im willing to see you make a pull request :smile:

**Comment by BennyVL** [comment]
Sorry, I am not familiar with the process and currently am lacking the time to get into that. 
Maybe one day ... ;-)

Maybe someone else already knows how to this and is willing to step in?

**Comment by wayou** [comment]
what you wanna by setting the target attribute?

**Comment by BennyVL** [comment]
I am using your plugin on a grid of partner logo's. These logo's all have links to there respective external sites (target="_blank"). When your plugin is activated it does pick up the href of the parent a-element but not it's target attribute. Because of that the sites no longer open in a separte tab, which of course is not the desired behaviour. By including the suggested code the target is picked up as well and everything works again as expected.

**Comment by wayou** [comment]
oh i got it. and fixed :)
