### ISSUE TITLE
What if there is <script> in the data-caption?

### ISSUE THREAD

**Issue by Noitidart** [wayou/SlipHover#21]
If I put `<script>` into my `data-caption` field, will `jQuery.html` dangerously evaluate it here: https://github.com/wayou/SlipHover/blob/dc4dd2ee4e10c910f135d367637f4e9fadac8db9/src/jquery.sliphover.js#L137-L167 ?

Thanks sir for your great work.

**Comment by Noitidart** [comment]
Is it save if I do `.parseHTML` instead of the `.parse`?

**Comment by wayou** [comment]
i think there's no reason for someone who put script into it to hack himself.
what's more, the html is needed for customizing the look.
