### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by Ynk33** [wayou/SlipHover#24]
Hello,
Thanks for this amazing tool. But I can't manage to have multiple instances of sliphover on the same page.
I'd like to have 2 overlays on my items, but only the first one to declared seems to work.
Here is a JS snippet where I declare my overlays : 

`$('#freewall').sliphover({`
    `backgroundColor: 'rgba(255,255,255,0.8)',`
    `target: '.item'`
`});`
`$('#freewall').sliphover({`
`height: '30%',`
`fontColor : '#ffffff',`
`backgroundColor : 'rgba(0,0,0,0.8)',`
`target : '.item img',`
`withLink : true`
`});`

Am I doing something wrong? Or is this not possible for the moment?
Thanks for your help.

**Comment by wayou** [comment]
I'm afraid it's impossible  to have multi instance.

I wonder why you wanna 2 overlay over an item ❓

**Comment by Ynk33** [comment]
I use one to have a white border around my items (playing with z-index to have the overlay in bg), and another one to have a real black overlay with the item name in it.
Have you any suggestion?

**Comment by wayou** [comment]
I think you'd better make the white border with just css :(
