### ISSUE TITLE
Any compatible lightbox

### ISSUE THREAD

**Issue by seldimi** [wayou/SlipHover#26]
Hey.
Is there any way we can create a lightbox over sliphover images?

**Comment by wayou** [comment]
could you please setup a jsfiddle?

**Comment by seldimi** [comment]
There you go... I have added swipebox, but lightbox works the same way. I want on click to get the image loaded on that lightbox
https://jsfiddle.net/jqtnyLs6/2/

**Comment by wayou** [comment]
I'm afraid the two cannot work together for sliphover create a mask over images and take over the click event.

**Comment by seldimi** [comment]
Yes I have already knew that. Can you make anything in next versions that can be combined with lightbox? Its great effect for gallery but no image preview makes it worthless

**Comment by wayou** [comment]
wait, i think there's a workaround worth trying.
that is to add an option to disable the the mask to take over the click event, i will try tomorrow and let you know if works.

**Comment by wayou** [comment]
unfortunately, cannot get it work.  
i tried using `pointer-events` but breaks the sliphover functionality.

**Comment by seldimi** [comment]
Isn't there any way mask to inherit click events from image (or attributes)? Some lightbox plugins have a data attribute or rel attribute to links in order to load image on lightbox

**Comment by wayou** [comment]
basically the sliphover create mask according the `mouseover` and `mouseleave` events, and then the image is not clickable when the mask shows. 
 i tried to set `pointer-events: none` for the mask and all its children and make the original DOM clickable, but here another problem comes, the `pointer-events: none` also takes the `mouseleave` away.
